### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by eddiewong396** [Arc676/Toohak#10]
Hello.

Update : 
Before I was try to execute the codes, not the compiled jar file. Running the jar file, downloaded from the released page, works.

Now I am trying to edit the codes to replace the g.drawstring to JLabel. May I know how to compile it with the changes?

Previous Post :
I'm downloaded the files and tried to run it but it gives an error : 
<img width="488" alt="Screen Shot 2019-06-27 at 2 11 54 PM" src="https://user-images.githubusercontent.com/685104/60241296-89e61200-98e5-11e9-9ebc-cfe6ac986679.png">

I tried to search for the error in the console but couldn't find it.

I also tried using the terminal with java -jar commons-cvs-1.5.jar and outputs an error :
no main manifest attribute, in commons-csv-1.5.jar

Am I doing something wrong?

My java version is java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by Arc676** [comment]
You will need to install a JDK (Java development kit) if you don’t already have one in order to compile Java code. You can use the one provided by Oracle (which was used during development) or the OpenJDK.

**Comment by eddiewong396** [comment]
I have the JDK installed but which file do I need to compile? It outputs an error stating that it can't find the other files in the other folder.

**Comment by Arc676** [comment]
Do you have an IDE as well or are you compiling from the command line? The main file is `src/main/Main.java` (has the `main` method in it). The Apache jar file is a dependency of the project. During development I used Eclipse.

**Comment by eddiewong396** [comment]
I'm trying to compile it from the command line. I will try and get an IDE to compile and get back to you.
