### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by alejokalderon** [Arc676/Toohak#6]
Hi,

I'm not a developer but I want to try your software, ¿Could you please help me to know how to use on a LAN network? 

Regards!

**Comment by Arc676** [comment]
Sure! Thanks for your interest in the project.

You need to create a quiz in order to host a game. Once the quiz is saved, clicking "Host Game" will ask you to pick the quiz file. Then, your IP address will be displayed.

Other people can click "Join Game" and enter your IP address as well as a desired username to join your game.

**Comment by alejokalderon** [comment]
Thank you for your fast response, I'm so glad.

But I cannot open the files, I already downloaded the zip and uncompress it. What I should do rigth now?

Thank you again!

Regards!

**Comment by Arc676** [comment]
You need to have Java installed to run Toohak.

**Comment by alejokalderon** [comment]
Hi, I'm trying to install Toohak but I can't. I already have jdk, and jre. I already download the source zip and I tryed to use Javac and java -jar to commons-csv-1.5.jar the same to src/main/Main.java and I don't know how to launch. Could you help me please? 

Thank you again, I think Toohak is a really good project!

Regards!

**Comment by Arc676** [comment]
If you have Java installed, you can simply run the JAR file available for download from the [release](https://github.com/Arc676/Toohak/releases/tag/v1.0).

**Comment by alejokalderon** [comment]
Thank you for your help and sorry. I didn't see the compiled version.

Regards!

**Comment by Arc676** [comment]
No problem. Let me know if you have other questions.

**Comment by arushibohra** [comment]
hi
i have a mac
can you please tell me steps to run this project as i am newbee

**Comment by Arc676** [comment]
As stated previously, you need to have Java installed to run Toohak. You can download the JAR file from the releases and run it just by opening it. If you want to compile it yourself, you can look up how to import projects for your IDE of choice.

**Comment by arushibohra** [comment]
i am trying to run the jar file
it gives a prompt saying :
The java jar file "commons-csv-1.5.jar" could not be launched
check console for possible error messages
i have jre and jdk both installed

**Comment by Arc676** [comment]
The releases are [here](https://github.com/Arc676/Toohak/releases/tag/v1.0), same link as posted previously. The CSV JAR is a library used to compile the project.
