### ISSUE TITLE
How to run toohak in window? Do you have the step by step procedure pls?

### ISSUE THREAD

**Issue by roslansidek** [Arc676/Toohak#9]
I want to try toohak, but i dont know how to run it in window

**Comment by Arc676** [comment]
Are you still having trouble?

**Comment by SAMKIT2711** [comment]
I AM FACING ISSUES..
I AM USING NETBEANS LTS 11 AND JDK 8 VERSIONS
I AM NOT ABLE TO IMPLEMENT IN WINDOW WOULD U GIVE PROCEDURE PLZ?
